name: Deploy docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - .github/workflows/docs.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
