name: Deploy docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'benchmark/**'
      - package.json
      - .github/workflows/docs.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Run benchmark
        uses: nuxt/actions-yarn@master
        with:
          args: docs:prepare
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
