name: Deploy docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'benchmark/**'
      - package.json
      - .github/workflows/docs.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Run benchmark
        run: yarn docs:prepare
      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: docs
          GH_PAT: ${{ secrets.GH_PAT }}
