name: Publish package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: nuxt/actions-yarn@master
        with:
          cmd: install
      - name: Publish package
        uses: nuxt/actions-yarn@master
        with:
          cmd: publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
