name: Test and Lint

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: nuxt/actions-yarn@master
        with:
          cmd: install
      - name: Run tests
        uses: nuxt/actions-yarn@master
        with:
          cmd: test
      - name: Lint files
        uses: nuxt/actions-yarn@master
        with:
          cmd: lint
