name: Test and Lint

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Lint files
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
